.pragma library

var SPACING = 10
var BORDER_COLOR = "#696969"
var COLOR_GREEN = "#E0FFE0"
var COLOR_BLUE = "#BDE0FF"
var COLOR_GRAY = "#F0F0F0"
var MIN_ITEM_FONT_SIZE = 12
var MAX_ITEM_FONT_SIZE = 18
var MIN_HEADER_FONT_SIZE = 20
var MAX_HEADER_FONT_SIZE = 40

